--------------------------------------------------------
--  File created - Tuesday-February-11-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RAWNAV_BW_MESSAGE
--------------------------------------------------------

  CREATE TABLE "PLANAPI"."RAWNAV_BW_MESSAGE" 
   (	"ID" NUMBER, 
	"SVC_DATE" VARCHAR2(20 BYTE), 
	"THE_TIME" VARCHAR2(20 BYTE), 
	"BUS_ID" VARCHAR2(20 BYTE), 
	"MESSAGE" VARCHAR2(120 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLANAPI_T" ;
--------------------------------------------------------
--  DDL for Index RAWNAV_BW_MESSAGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PLANAPI"."RAWNAV_BW_MESSAGE_PK" ON "PLANAPI"."RAWNAV_BW_MESSAGE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLANAPI_T" ;
--------------------------------------------------------
--  Constraints for Table RAWNAV_BW_MESSAGE
--------------------------------------------------------

  ALTER TABLE "PLANAPI"."RAWNAV_BW_MESSAGE" ADD CONSTRAINT "RAWNAV_BW_MESSAGE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLANAPI_T"  ENABLE;
  ALTER TABLE "PLANAPI"."RAWNAV_BW_MESSAGE" MODIFY ("ID" NOT NULL ENABLE);
